;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Dec 6 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
SSG SEGMENT PARA STACK 'STACK'
        DW 16 DUP(?)
SSG ENDS

DSG SEGMENT PARA 'DATA'
    PORT_A 	  DW  00d
    PORT_B	  DW  02d
    PORT_CONTROL  DW  06d
    
    CTRL_REG_DATA DB  10000010b
    
    DISPLAY_0     DB 11000000b
    DISPLAY_1     DB 11111001b
    DISPLAY_2     DB 10100100b
    DISPLAY_3     DB 10110000b
    DISPLAY_4     DB 10011001b
    DISPLAY_5     DB 10010010b
    DISPLAY_6     DB 10000010B
    DISPLAY_7     DB 11111000B
    
    ; DISPLAY_8     DB we just have 8 btns
    ; DISPLAY_9     DB
    
DSG ENDS

CSG SEGMENT PARA 'CODE'
                    ASSUME SS:SSG, DS:DSG, CS:CSG

MAIN PROC FAR
                    PUSH   DS
                    XOR    AX, AX
                    PUSH   AX
               
                    MOV    AX, DSG
                    MOV    DS, AX

		    ; SET 8255 MODE
		    MOV DX, PORT_CONTROL
		    MOV AL,  CTRL_REG_DATA
		    OUT DX,AL
		    
		    ; DISPLAY 0
		    MOV DX, PORT_A
		    MOV AL, DISPLAY_0
		    OUT DX,AL
		    
	READ:	
		    ; READ PUSH BUTTONS
		    MOV DX, PORT_B
		    IN AL,DX
		    
		    ; SET PORT TO WRITE
		    MOV DX, PORT_A
		    
		    ; COMPARE WHICK BUTTON PRESSED
		    CMP AL, 11111110b
		    JE S0
		    CMP AL, 11111101b
		    JE S1
		    CMP AL, 11111011b
		    JE S2
		    CMP AL, 11110111b
		    JE S3
		    CMP AL, 11101111b
		    JE S4
		    CMP AL, 11011111b
		    JE S5
		    CMP AL, 10111111b
		    JE S6
		    CMP AL, 01111111b
		    JE S7
		    JMP READ ; IF NONE OF THEM PRESSED READ AGAIN
	DISPLAY:
		    OUT DX,AL
		    JMP READ

		     ; DISPLAY NUMBER AT 7DIGIT
		  S0:
		   MOV AL, DISPLAY_0
		   JMP DISPLAY
		  S1:
		   MOV AL, DISPLAY_1
		   JMP DISPLAY
		  S2:
		   MOV AL, DISPLAY_2
		   JMP DISPLAY
		  S3:
		   MOV AL, DISPLAY_3
		   JMP DISPLAY
		  S4:
		   MOV AL, DISPLAY_4
		   JMP DISPLAY
		  S5:
		   MOV AL, DISPLAY_5
		   JMP DISPLAY
		  S6:
		   MOV AL, DISPLAY_6
		   JMP DISPLAY
		  S7:
		   MOV AL, DISPLAY_7
		   JMP DISPLAY


MAIN ENDP

CSG ENDS
END MAIN